#!/usr/bin/env bash

brew update
brew tap rsteube/homebrew-tap
brew install rsteube/tap/carapace starship nushell

ls ~/.config/nushell/env.nu 2>/dev/null

if [[ $? -eq 2 ]]; then
  while :; do
    _credentials=$(echo "host=github.com" | gp credential-helper get)
    _password=$(echo $_credentials | grep password=)

    if [[ -n $_password ]]; then
      break
    else
      echo "Waiting for credentials..."
      sleep 1
    fi
  done

  echo "Creating and cloning nushell-files..."

  mv ~/.config/nushell ~/.config/nushell.1
  git clone https://github.com/jondpenton-org/nushell-files.git ~/.config/nushell/
  sudo mv ~/.config/nushell.1/* ~/.config/nushell/
  sudo rm -rf ~/.config/nushell.1/
fi
